services:
  web:
    build:
      context: ./
      target: runner
    volumes:
      - .:/app
    command: npm run dev
    ports:
      - 3333:3000
    environment:
      NODE_ENV: development
    env_file: .env.local
